### PR TITLE
Adding a link to WikiData SDK npm package

### PR DESCRIPTION
**Pull request by Hunter-Github**
One of the easiest to use frameworks for WikiData out there.

### CODE REVIEW

**Comment by emijrp** [comment]
Thanks!

**Comment by waldyrious** [comment]
Was it intentional that the link points to the issues page?

**Comment by Hunter-Github** [comment]
Definitely not. Thanks for spotting!

**Comment by emijrp** [comment]
I corrected it just after the merge.

**Comment by waldyrious** [comment]
:+1:

**Pull request merged**
